name: mlflw-ci

on: 
  push:
    branches: ["master"]

env:
  IMAGE_NAME: churn-mlflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mlflow-churn .
          docker tag mlflow-churn:latest akash300/mlflow-churun:latest

      - name: Run linting and formatting checks
        run: |
          pip install -r requirements.txt
          pytest main.py
          black --check main.py

      - name: code review
        uses: reviewdog/action-eslint@v1
        with:
          eslint_github_token: ${{ secrets.GITHUBTOKEN }}
          eslint_level: error
          eslint_flags: '--fix'
          eslint_pattern: '**.py'
          
      


